ARG ARCH
FROM ${ARCH}python:slim

WORKDIR /usr/src/app

COPY requirements requirements
RUN pip install --no-cache-dir -r requirements && rm requirements

COPY src .
COPY config /config
EXPOSE 8080

ENTRYPOINT ["python3", "/usr/src/app/main.py"]
