apiVersion: v1
kind: Service
metadata:
  name: opserver
  namespace: quality-assurance
  labels:
    app: opserver
spec:
  selector:
    app: opserver
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
