#apiToken: "secret-token"
clusterURL: "https://rancher-url/v3"
clusters:
  - name: "prod" 
    ingress: "ingress.com"
    environment: ["prod", "gcp"]
  - name: "dev"
    ingress: "dev.ingress.com"
    environment: ["dev", "internal"]
debug: False
proxy: True
verify: False