apiVersion: v1
kind: Service
metadata:
  name: {{ include "opserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opserver.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "opserver.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
