apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "opserver.labels" . | nindent 4 }}
  name: {{ include "opserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "opserver.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opserver.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
      {{- range $index, $s := . }}
        - {{- print "registry-" $index }}
      {{- end }}
      {{- end }}
      containers:
        - env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "opserver.fullname" . }}-secret
                  key: API_TOKEN
          image: "{{ default "docker.io" .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              hostPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: {{ include "opserver.fullname" . }}-config
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      volumes:
        - name: {{ include "opserver.fullname" . }}-config
          configMap:
            name: {{ include "opserver.fullname" . }}-config
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
