apiVersion: v1
data:
  config.yaml: |
    {{- toYaml .Values.config.config | nindent 4 }}
  limits.yaml: |
    {{- toYaml .Values.config.limits | nindent 4 }}
kind: ConfigMap
metadata:
  name: {{ include "opserver.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opserver.labels" $ | nindent 4 }}
