{{- if .Values.image.imagePullSecrets }}
{{- range .Values.image.imagePullSecrets}}
{{- if and (hasKey . "registry" ) (hasKey . "username") }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "opserver.labels" $ | nindent 4 }}
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
---
{{- end }}
{{- end }}
{{- end }}