{{- if .Values.ingress.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    {{- include "opserver.labels" . | nindent 4 }}
  name: opserver
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.ingress.config }}
  gateways:
    {{- if .gateways }}
    {{- range .gateways }}
    - {{ . }}
    {{- end }}
    {{- else }}
    - "istio-system/istio-ingress-gateway"
    {{- end }}
  hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
  http:
    {{- range .paths }}
    - match:
        - uri:
            exact: /{{ trimAll "/" . }}
      redirect:
        uri: /{{ trimAll "/" . }}/
    - match:
        - uri:
            prefix: /{{ trimAll "/" .  }}/
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ include "opserver.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local
            port:
              number: 8080
    {{- end }}
  {{- end }}
{{- end }}