{{- if .Values.image.imagePullSecrets }}
{{- range $index, $registry := .Values.image.imagePullSecrets}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "opserver.labels" $ | nindent 4 }}
  name: {{ print "registry-" $index }}
  namespace: {{ $.Release.Namespace }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" $registry }}
type: kubernetes.io/dockerconfigjson
---
{{- end }}
{{- end }}