name: opserver CI

on:
  workflow_dispatch:

jobs:
  debian:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'infologistix/opserver' }}
    steps:
        - name: Checkout Files
          uses: actions/checkout@v4
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v3
          id: qemu-debian
          with:
            platforms: linux/arm/v7,linux/arm64,linux/amd64
        - name: Setup BuildKit
          uses: docker/setup-buildx-action@v3
          id: buildx-debian
        - name: Dockerhub login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and Push Images
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ${{ github.repository }}:latest,${{ github.repository }}:slim
            context: .
            file: Dockerfile.debian
            platforms: linux/arm64,linux/amd64
  alpine:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'infologistix/opserver' }}
    steps:
        - name: Checkout Files
          uses: actions/checkout@v4
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v3
          id: qemu-alpine
          with:
            platforms: linux/arm/v7,linux/arm64,linux/amd64
        - name: Setup BuildKit
          uses: docker/setup-buildx-action@v3
          id: buildx-alpine
        - name: Dockerhub login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and Push Images
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ${{ github.repository }}:alpine
            context: .
            file: Dockerfile.alpine
            platforms: linux/arm64,linux/amd64
